AWSTemplateFormatVersion: '2010-09-09'
Outputs:
  FunctionName:
    Description: function name
    Value:
      Ref: LambdaFunctionHelloWorld
  StreamARN:
    Description: stream arn
    Value:
      Fn::GetAtt:
      - KinesisStream
      - Arn
Resources:
  KinesisStream:
    Properties:
      ShardCount: 1
    Type: AWS::Kinesis::Stream
  LambdaFunctionHelloWorld:
    Properties:
      CodeUri: s3://kevin-kinesis-to-lambda/28cd88f5a70c8995ddf8ba58445babe1
      Events:
        HelloWorldApi:
          Properties:
            Method: GET
            Path: /
          Type: Api
        Stream:
          Properties:
            BatchSize: 100
            StartingPosition: LATEST
            Stream:
              Fn::GetAtt:
              - KinesisStream
              - Arn
          Type: Kinesis
      Handler: index.handler
      Runtime: nodejs8.10
      Timeout: 10
      Tracing: Active
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
