AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  LambdaFunctionHelloWorld:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs8.10
      Timeout: 10
      Tracing: Active
      Events:
        HelloWorldApi:
          Type: Api
          Properties:
            Path: /
            Method: GET
        Stream:
          Type: Kinesis
          Properties:
            Stream: !GetAtt KinesisStream.Arn
            BatchSize: 100
            StartingPosition: LATEST
  KinesisStream:
    Type: AWS::Kinesis::Stream
    Properties:
      ShardCount: 1
  MyKinesisAnalytics:
    Type: AWS::KinesisAnalytics::Application
    Properties:
      ApplicationName: "sampleAnalyticsApp"
      ApplicationDescription: "sampe analytics app description"
      ApplicationCode: "sample app code"
      Inputs:
        - NamePrefix: "sampleAppPrevix"
          InputSchema:
            RecordColumns:
              - Name: "example"
                SqlType: "INTEGER"
                Mapping: "$.example"
            RecordFormat:
              RecordFormatType: "JSON"
              MappingParameters:
                JSONMappingParameters:
                  RecordRowPath: "$"
  KinesisAnalyticsRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: kinesisanalytics.amazonaws.com
            Action: "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: Open
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: "*"
                Resource: "*"
Outputs:
  FunctionName:
    Description: "function name"
    Value: !Ref LambdaFunctionHelloWorld
  StreamARN:
    Description: "stream arn"
    Value: !GetAtt KinesisStream.Arn